AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RoleName:
    Type: String



Resources:
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ec2-sg
      GroupDescription: Allow SSH and HTTP access only MyIP
      VpcId: !ImportValue CrossStackMyVPC
      SecurityGroupIngress:
        # http
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        # ssh
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref RoleName

  EC2: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-00d101850e971728d
      InstanceType: t2.micro
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          SubnetId: !ImportValue CrossStackPrivateSubnet
          GroupSet:
            - !Ref EC2SG
      IamInstanceProfile: !Ref EC2InstanceProfile
      Tags:
          - Key: Name
            Value: ec2-cf