AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # VPC作成
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        -
          Key: Name
          Value: MyVPC

  # サブネット作成
  privateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: false
      VpcId: !Ref MyVPC
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
      Tags:
        - Key: Name
          Value: privateSubnet

  # ルートテーブル
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: MyRouteTable

  # サブネットとルートテーブルを紐づけ
  assocciateRouteTableForPrivateSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MyRouteTable
      SubnetId: !Ref privateSubnet

# リソースをoutputする
Outputs:
  CrossStackMyVPC:
    Value: !Ref MyVPC
    Export:
      Name: CrossStackMyVPC
  CrossStackPrivateSubnet:
    Value: !Ref privateSubnet
    Export:
      Name: CrossStackPrivateSubnet
  CrossStackRouteTable:
    Value: !Ref MyRouteTable
    Export:
      Name: CrossStackRouteTable
