AWSTemplateFormatVersion: "2010-09-09"

# 参考
# https://dev.classmethod.jp/articles/cloudformation-ssm-manager-automate-cloudwatch-agent-installation
# precondition
# https://docs.aws.amazon.com/ja_jp/systems-manager/latest/userguide/documents-schemas-features.html

Resources:
  SSMParameterLinuxLogs:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "AmazonCloudWatch-Linux"
      Description: "SSM Parameter for Linux"
      DataType: "text"
      Tier: "Standard"
      Type: "String"
      Value: |
        {
          "agent": {
            "metrics_collection_interval": 60,
            "run_as_user": "cwagent"
          },
          "metrics": {
            "aggregation_dimensions": [
              [
                "InstanceId"
              ]
            ],
            "append_dimensions": {
              "InstanceId": "${aws:InstanceId}"
            },
              "cpu": {
                "measurement": [
                  "cpu_usage_idle",
                  "cpu_usage_iowait",
                  "cpu_usage_user",
                  "cpu_usage_system"
                ],
                "metrics_collection_interval": 60,
                "resources": [
                  "*"
                ],
                "totalcpu": false
              },
              "disk": {
                "measurement": [
                  "used_percent",
                  "inodes_free"
                ],
                "metrics_collection_interval": 60,
                "resources": [
                  "*"
                ]
              },
              "diskio": {
                "measurement": [
                  "io_time",
                  "write_bytes",
                  "read_bytes",
                  "writes",
                  "reads"
                ],
                "metrics_collection_interval": 60,
                "resources": [
                  "*"
                ]
              },
              "mem": {
                "measurement": [
                  "mem_used_percent"
                ],
                "metrics_collection_interval": 60
              },
              "netstat": {
                "measurement": [
                  "tcp_established",
                  "tcp_time_wait"
                ],
                "metrics_collection_interval": 60
              },
              "swap": {
                "measurement": [
                  "swap_used_percent"
                ],
                "metrics_collection_interval": 60
              }
            }
          }
        }
  ## Windows
  SSMParameterWindowsLogs:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "AmazonCloudWatch-Windows"
      Description: "SSM Parameter for Windows"
      DataType: "text"
      Tier: "Standard"
      Type: "String"
      Value: |
        {
          "agent": {
            "metrics_collection_interval": 60
          },
          "metrics": {
            "aggregation_dimensions": [
              [
                "InstanceId"
              ]
            ],
            "append_dimensions": {
              "InstanceId": "${aws:InstanceId}"
            },
            "cpu": {
              "measurement": [
                "cpu_usage_idle",
                "cpu_usage_iowait",
                "cpu_usage_user",
                "cpu_usage_system"
              ],
              "metrics_collection_interval": 60
            },
            "disk": {
              "measurement": [
                "disk_used_percent"
              ],
              "metrics_collection_interval": 60,
              "resources": [
                "*"
              ]
            },
            "mem": {
              "measurement": [
                "mem_used_percent"
              ],
              "metrics_collection_interval": 60
            }
          }
        }

  InstallAndManageCloudWatchDocument:
    Type: "AWS::SSM::Document"
    Properties:
      DocumentType: Command
      Name: InstallAndManageCloudWatchDocument
      UpdateMethod: NewVersion
      Content:
        schemaVersion: "2.2"
        description: "The AWS-InstallAndManageCloudWatch command document installs the Amazon CloudWatch agent and manages the configuration of the agent for Amazon EC2 instances."
        mainSteps:
          - name: installCWAgent
            action: "aws:runDocument"
            inputs:
              documentType: SSMDocument
              documentPath: AWS-ConfigureAWSPackage
              documentParameters:
                action: Install
                name: AmazonCloudWatchAgent
          - name: manageCWAgentLinux
            action: "aws:runDocument"
            precondition:
              StringEquals:
                - platformType
                - Linux
            inputs:
              documentType: SSMDocument
              documentPath: AmazonCloudWatch-ManageAgent
              documentParameters:
                action: configure
                mode: ec2
                optionalConfigurationSource: ssm
                optionalConfigurationLocation: !Ref SSMParameterLinuxLogs
                optionalRestart: "yes"
          - name: manageCWAgentWindows
            action: "aws:runDocument"
            precondition:
              StringEquals:
                - platformType
                - Windows
            inputs:
              documentType: SSMDocument
              documentPath: AmazonCloudWatch-ManageAgent
              documentParameters:
                action: configure
                mode: ec2
                optionalConfigurationSource: ssm
                optionalConfigurationLocation: !Ref SSMParameterWindowsLogs
                optionalRestart: "yes"

  SystemAssociationForInstallAndConfigureCloudWatchAgent:
    Type: "AWS::SSM::Association"
    Properties:
      Name:
        Ref: InstallAndManageCloudWatchDocument
      AssociationName: ManageCloudWatchAgent
      ScheduleExpression:
        Ref: "AWS::NoValue" # スケジュールしない
      Targets:
        - Key: InstanceIds
          Values:
            - "*" # 全てのインスタンスまたはインスタンスID